services:

  pearlsaqi:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: pearlsaqi

    restart: "no"

    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs

    environment:
      PYTHONUNBUFFERED: "1"

    ports:
      - "8000:8000"

    networks:
      - pearlsaqi_network


      


networks:
  pearlsaqi_network:
    driver: bridge